# This is a config for E2B sandbox template.
# You can use template ID (07d5m6pkkc1f8hymzpkw) or template name (devflow-nextjs-test-v7) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("devflow-nextjs-test-v7") # Sync sandbox
# sandbox = await AsyncSandbox.create("devflow-nextjs-test-v7") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('devflow-nextjs-test-v7')

team_id = "0a8209b1-f230-4edf-bc33-13691a5285b4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "devflow-nextjs-test-v7"
template_id = "07d5m6pkkc1f8hymzpkw"
